apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: mekar43/webserver
        name: webserver
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_USER
          value: "clarus"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: mysql-admin-password
        - name: MYSQL_DATABASE
          value: "phonebook"
        - name: MYSQL_DATABASE_HOST
          value: "mysql-service.default.svc.cluster.local"
